package entity;
// Generated 06-Jul-2024 15:33:06 by Hibernate Tools 4.3.1



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Long id;
     private String name;
     private String email;
     private String address;

    public Employee() {
    }

	
    public Employee(String name) {
        this.name = name;
    }
    public Employee(String name, String email, String address) {
       this.name = name;
       this.email = email;
       this.address = address;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


